apiVersion: v1
kind: Service
metadata:
  name: stock
  namespace: oms
  labels:
    app: stock
    component: backend-service
    app.kubernetes.io/name: stock
    app.kubernetes.io/part-of: oms
spec:
  type: ClusterIP
  ports:
  - port: 9003
    targetPort: 9003
    protocol: TCP
    name: grpc
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: stock
