apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Configuration management for local-k3d environment

resources:
- secrets.yaml
- postgres-init-configmap.yaml

patches:
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: oms-config
- path: payments-env-patch.yaml
  target:
    kind: Deployment
    name: payments
