apiVersion: v1
kind: Service
metadata:
  name: customer-app
  namespace: oms
  labels:
    app: customer-app
    component: frontend
    app.kubernetes.io/name: customer-app
    app.kubernetes.io/part-of: oms
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: customer-app
