apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Infrastructure services for dev environment
# Includes PostgreSQL, MongoDB, RabbitMQ, Redis, Consul

resources:
- infrastructure.yaml
