apiVersion: v1
kind: Service
metadata:
  name: kitchen-display
  namespace: oms
  labels:
    app: kitchen-display
    component: frontend
    app.kubernetes.io/name: kitchen-display
    app.kubernetes.io/part-of: oms
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: kitchen-display
