---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: stripe-secrets
  namespace: oms
spec:
  encryptedData:
    STRIPE_ENDPOINT_SECRET: AgC5WI1TycqDLfXw/sHs8iDZelxolEkrz9DguAV3i07D4Xqcq1bstJ5TRVTxgThnKLRE05lr77Uxc2yD/5/lNUNVcWc783tfxVZ4wSw1ewL3YjVN25jXHkBnOYjfaGP1MeRa3o8NMhlP0uPbrLSm4dTEXvjyeQvutxbQfG2vid85fqZ28tFPG4t/iXcDYnfFSBwHi4dJ6zDxAtDm8vQ8A9VeYdhTowOQuIeO53u9VCTXshk37zu08RmInCLQAB8jtvzjNTqQi6tFSU2HGgw3vTzakdqP96zYSVZdKKsftDNeDvX7k80Z59mLYrNw/xT8wxmvo9FdbSLvyHIqQCPv6dHjFdAgy2WDvv5+Ye56qsP8teki0/kUGf3MzgJbN5PhLANcOb9fTjmjflZ6Tr+D+KbCGXnfWK2Eb/CEGH/29jutZ8J+rbm8I38+I2z171noKYqolCD27yYzObUue5LaeZzcBjrCrV1Rnz68joxuqDBAebsWXgU6+qkPObxbZ6M0PF03zu+euxYhCxF1PSokPkbkdVf/0+zz8jlgxmCfE6aFwyarIEnSbTwlWKAQhl3IZD+4jzmonBSLQFOSJ8qxWE9XCHsdfTWk39aCts+EUck0tUy7ygEU62T4FO/f8/l5W8aYxEhj0/W0/q7T12nmd/S3LoNvZeeUNE/xPHbS53ucl+T7My0iRxKfeZgPcgI8mRaz/0lxT/MwIdGfoQqiNSQ8Chv6hIeqMC2wchJioi6TIuVWboeBkw==
    STRIPE_SECRET_KEY: AgCqd9WnUCITfbqsLZOSSTGRxDt34K8BIY6LGQdKCjnvToDjQznmSlyuHMthA8vPTOJ12YQlqNlZIPc0UmgRcsbJPetaOfr9iZxTzlbesScB5twd6Sspn2Uhg2/s/WO2jyiRVHbjY5ytc/PZ24iKLdLlKE3GdKtY1KNnpdad+zOGfSJF73PfuAib4M/2ux9xp/2EFxg1+tk4OIW4TJDlCe+quxEfykWmTbMr+enNX0OriBenJrYehVRi7x37hVxjnrya6hzBHPVdvGAN7p7FRnPvMGz9rZ1dNpIdSV43q0Ye8jyhF/hHPQdO/aGkCeEljWHNBYqSByf3WEpvbnDxXhjGwiWi4jiknCdQmAakNy5UcrB9GjPFTR46KXI4hH4/ee80XpjpbkrZBlCLsy4GX0CH3vpIOQcW7NoI3mZI8/agrcPH0TbOl6bSTG/rXaEmM7eZ5Se0YY9G0BPR8wcw0SKdHfMGRRulB4bngLIm+CUmtgzyyjgHpAsGMFdm7mMPHShKMmmtYsUNiEHX38baNQd4JEPtJ3wB6wcXhFc8zbrRrSMfKcVan9y8WNHqEpjL/QxyCEcpRqz5M3Chrs+WltY4W85hQKPs70fxxvoFQdYyq2KZUECw4h7ztOGYkJ8P9WwxT00b3LUiuEQO23woZGUuMpMUPQ3ws2LAcM0lMeTyiO/C83UFfTFTiWvKhrJxgo4ukNT+blbcPnlMXRV5JjAf2mDOcVHIAZqPGGLYav2gcIPsbrfxDao2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stripe-secrets
        app.kubernetes.io/part-of: oms
        environment: production
      name: stripe-secrets
      namespace: oms
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-secrets
  namespace: oms
spec:
  encryptedData:
    MONGODB_PASSWORD: AgBhpn2/VARVG/hTcJCyTPRG6qVT4DHPi0W7gLTtlCpdPSegFguW5NMxGI2Eqw0Svxz8seePkJjynHvwK7e1GSwAQy3A6oNU23WTh6CcY3nG6p6eF+iNaMozm8FMXyLLlJJZIAmtCh1GDdSvofqFvENDEJZikqdaoM6p2MdTjcV5Oto+ws5nsdXbeftFNHi8XUgqvbbbZM6vKqKemL3U2U2EIO5njuLW9FG0Pj4R3HWKUJwWNPXwNMkOH/0AKVSyGL3RROevVGE7q/cllMz0vAU/d/JQB4I3f+uPX9xbvUPKeBNkKWBasoplrGupcclmxd3/AU4Ia4AzdKy2nHUtukKRnKZTNW0+EI1k0rGmpNDo/azKG1bz/kFImDqaVcnLgzbwyho+nVMP0sXNSfeNVMxRQJpH7NZG65xYXq9H4QpFP+UXBrvUEhb+GZ6lTWNC5SxsIJhf5fNdcLJe/7Fj0wm5vM8vrWgRn+A8Rn5vpRbGjmtWwLBT2SmQ0uV0D6FFUYA6QyDmnACYA6ucKda2QY2RyuhsY1aJ7Pj+MMyTlrc3vNP5bLoXf5iuDm5ns2QUjhR2y3dz9vcHemOdgjUTc7VLlfPcyMddO8ETcOgXjZ2KyIm4cf/wIBk6RDQPJi89M7QvYLqrGVQh1SThGwvp4MN4oU72aA5A++VvtrBoOszLZyMMKhLblNsxDOp4Nyu6PWMIUjnXbuw3KQTalxqnL9grz+1tWIGOalCEpiK4
    MONGODB_URI: AgCNqbskGLlA3D7sZsYXmrouVKIdP2PlzhbeFu9K1RjHxR+MOLd7ZY0dq1hPWmKU04hPXhLpsen2PubLZE2ufte7WfFNusz9NfR3iKPPim9ilQy/LocfEttlGnKyWybMrtjycIA13m1coq+JBrz+Udt/RrtDzsK2BT5o2dro5uFuuHcSGcyFC0JxvTMd0IuhpC28CMHWVWzzNvFP4D53hX1gwqu7k9T/Hrb5SEs1kVnYBEAa3HkjovREKb+buo5GC+GN9pFPNu6gOKbJe8eci6CWNEWeJpwoCCeckvolyCyL/Rr3cxezL1VFKIB8xI+LFlAmrdNo4tZC5I6jPecz893ZyqNS2417pfjOUhkMojnFnl4LKhDHTyytTiKgkha7cNqufR5I8rA2FtnfgEgApkowS7kj86/IwIHdKjW4V39lM+DYQ0JPTvks3cts20/xVpkrWs3/Rqkz4SFswlup1z+k8R4gZdmRBlZyVNu2kNaBofvsCQD7hgUt6QDFB0XP1qsbnYwCIVK9iUKuX9WrBkm0BbHcE8AZ2Ng+Z1qm+lyHR8Nb4490AGsx5rN+2dZXySRaxPVN6cIZbTzxNjMzq0AkKSy0BtyGj3/tdPnXxRQ6pksVs4WVdyvzvRNqTpETWPyXZ35no+YhHTWFhJv7kKMi0zPLBg+PEnwEi846r7Ut8j4hSuCEXHCUW/W7nsq7mtc3EWwQtwoiB4eQ8echCwdiki29PlnnjbelS9JcyyxqdDfym7SXFM5E2AAVkgbTZn86D5lzdDj9+Aq+tPtBquP1TAo8Qc65U5Zdr7RBoyyhJo5Gnw/W9PzgHzxgn4xQgA4xoMC1AYw=
    POSTGRES_PASSWORD: AgCqKo/1NWWiqPYRWQ4l4ezRGNYVFgginxtlzwlyCiwXyL1AypWdNHt0m77ilgKu32EJvvtXdo5Rx2vw+4jculL9RWi8Apo0vQYihuxJWWLWsAUaXwkxbcwCqy210Sq6tAwJlKu16gkEtoh51+wxfVDyoZikNdEzhNY1cUIymButjpcJCnNmwnU4bn1nWdgddj0hmQUdLk8YFwazy7oL1876jZJbdlsvvhM+HrtrQ4HV848kskd5svN1/VN0dnQbUOg3BIymh5PkDFPAGm57aON/Pb4MRWcKd7BG1zqb82XpLaQ5tigPE9LglFH/giXxBfJjDnOSeiMKLjDcVWN1g/+tFfog9IAclQrgw9frX+pA3uAwjBGEmI9QI7M9ylQzgFeizRH3m1/WM2s+xm0PbDYkYfGx+4XI1CPrVFJcmAy99QNfLXJ4eSVlSvHbO/XPKqXxeBEsjM5B6IdQpdb/n4VEVb0nJoR/2xNqv7iWlrymza6VuYg3XpUYcIS7gXHfkw5Y1J07W0sRqKNrwBDfi8zjdYm1vYvl3JsOFoUnUgPxPYtbahzGkIdYypXCRN1oSgiQ7q9qTRsnoZS5bLoaf8OmvxLkS9qiWCVrVdoXU4LcJF+kewtil9MX2ETzKBRX35GQqFmETeLxwokTRhZC99t9542ItQmb+xNK4ziMpOfu7INqoVSF+tufh4Dp+/qd9ZZMPEOnOvuFNm/HLdExSQ2MIH0KMM1Z67TaiYsU
  template:
    metadata:
      labels:
        app.kubernetes.io/name: database-secrets
        app.kubernetes.io/part-of: oms
        environment: production
      name: database-secrets
      namespace: oms
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secrets
  namespace: oms
spec:
  encryptedData:
    RABBITMQ_PASSWORD: AgAZ4yg7NU2RrpvekxBo2/Yz2K43ahu6lFcSIFloNcnylU3sma0w++hGlBeV+BrPe3J8/WKPh6j/Kxh82rdvPHbfbEN8pp797Nqho7kOeMauBd0bd5EcL8FwPy6rJVuZzgsIolZ3rtS9H4GLBB8fdLO+TgGhQfpQNGuDmcTUmPkqof/g39eCBvhsYj09nSG8DoB1SVNdHW0lACi4gr9RgbMhf5sfj6aIFB4yFpnnuWG+/8ID7Cba/oD5Hg1XueDl0yC3zoQxdktryy/B0vFP74zz9ywpCTBadhrxyPNZh3+1NR68ArDlVgK1ajcAbCsYcscYgJI3u5Zl8ehY5Xm8FauxEKBpTBXzq6hATUMnFcwt6U5IDwKB+2sAhJC/vg48gthq+xUXP5W7Mecb/nrLAvaEt+gpTd2lO5V9G9QIsWux4eTuE2kp78V69bBtrUwaxHbOfhKs5iIYpfjQPz3OWYUT8PrxOAiLwvQbPaZCKty7n4HueZWXgUp01BMgaM6YsPQrWwLrnKOlrnbcaqG3i6vaDM5bzSZCotDXb6H1sMhUbjFfxF4ctkNM5ma0qlwE0DBy3oGyPoXlCAAROefWL4c8rZ0ReGLigtvh4fHJxtomvcz2zYSJJx6pAGuqdlhOXEwlF/Uy5HlH35FtKLl9aQvxR3aeUgyU2b3x53WQIPbb8z2PonmSgaL36Dd67fCtAeSHLx6/FOvkPNR2rUW2QKP5/i1KpoN3es3janYQ
    RABBITMQ_URL: AgB0xilxgf6Zk/itLsA6uNJ2ghiL6axPxTCpQ/vwzFcTkeu6jq6aHPopgg6XvBWzyFmxM42tE5vW0gILzkuZfHbZu1eGZSrge8wa4z76OAGiduLxKC+khS27zBb8lMgttyJ53CWQO54RgYWs8GRA1VwajBOIQCwYx/QvX+jjuWeILoa374jOBmK5c/MW1Sn0Zk1SMxa0pUJFrEnWAiJggEK+r17k7yMrpRC26XUBAP9mP8W9Q1KgWr47V2iNnS4cXX2PSe6LO8vGbVfYuO2e0gpDNZW2K5fceR/xWAnGTv2TWKEiSAG5zM66mhdu28BAcKzL2L6+hi38nfAqPhd/pxtCAbyXY+taxOHEr0TDt2cYdCS8piEmqOmofRhIRtj9PGPBWjsfHBNucr0MUJXNKpwNfuUt4yhRx6L73Hk426qMgIoAF/HHW4hGGXuWEBRQyHUwm5KJY//Sv7X0BLmM+r/q/PPw/hCKcT6ofDfEg6d7Uwm8uvp4cKb+KCjHSPv8/ZNRILRuOhsgDbLhs2s7FmwO0qPc8rRZPidsAJxRu4DBtBKk3oNS9TEJlooqZDtZhlzBfhLfojjgx49Qv3mRUH18uiOxW2fhvbA5J2wqnyv2P9i1yq0UYe5ZhgV8ucKNwlPB/97RSbk10XX2eFVPs7uy1fpKBRFMA4/K8LXc4lx/t4LV/z4OhztCWnx9jwRWyEUOjFkjtDoYHFXJ0nr3jMbYCQQu6+QeGIyvKd+QAmFij0z+Ne9/K4u5cIfa4h/WnsilwKFExpF3AhRd0cFwox5yHruYB/jPCZX4TrMYEs4=
    RABBITMQ_USER: AgAA3NvDZwVIlRXb2Jk4iBL5VMWXCur0BjXc5unzx7TjT+MWArVkUUHQ/x3soXGOHjtriE5Uhih6tF5i/7Yn0GyNkU0mdhyXAGry/CzwOdoioJwoINj4Vl84UoWp+Oz1vCl+/hQn/Ce+1mjj+Yb+FTlZtuKco9WHoNKHQ/wZ08cHocVsu297D+p1P+tq+PYdlQLN31ALPNgoW1mBAOWA/CbUm8o4AcY55vPh/ZtPW9BdElnI1yIwsv9hyihcAtT5UhkPkciPSMgInOPQtOW/vdMtEB9lZaYMWWUO7TeBwB6KM+voG8FMJ4xoxTTNxYY4tK1sfcxhnSIX0hwxzNpevuLHOG1S+PNg42qwbI8f2Nl0g3MG4HW6bkaXKZ6gr6jDUru0vRjKpzFMPA21nBxixL3Mqgrrsfaxyu5DgO9/mpRzL7HYJKdd1SOEWRxSHNstFvi9ANb6dkUo/T8xKmixqbrpM78v9MdyVvfkVqYoyH/H7oXmghqUSBL56qPKWd1bTWF0xbMr0AfZ4dYLap6gbIbY4p1j8ozkDJnxHBUIK5ax81htQ3zXedBp7jurMoOYPbPBa6hEr5O3mDWDSbwQC8ASPmC+XSZn31z03HxG2/8ys2fyGSKQA42Lu8XwR6grMb4X/UHInAJgJ+4Le0JyNlqO0UOK7nmxiMAKuRSHQIID9nGOo6Xw6Knps/qGTA1b5ryKSQEvM51DhDcc/ipvzg==
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq-secrets
        app.kubernetes.io/part-of: oms
        environment: production
      name: rabbitmq-secrets
      namespace: oms
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secrets
  namespace: oms
spec:
  encryptedData:
    REDIS_PASSWORD: AgCU96yGzaJpls8DFL5i5WFR3imZmggxehzzQ+Ul87XL3oCqNXeen+BA00J1R6tQiemg7T2L4mfoUcQwIaqwzY/bsCxogwjB9rPbmnGy7Kuf+PoWGTeff6n+le1/MDp5zlWOHoofeLKpbX359gBHb8G5/c634cgJErcJ7EBvWOSZrHrOqirUkIP4DxDAMsjzn7EFGuy+OZ020TDXWVpX6PTnT8xLAaJ7vPbUz9VckeFpNLaqcqk2gTMGvYlvYgBAt+vgAqekHAADpeQcsVRi8iDUdO33496d34pqSfo9pjj79e2ZpaEuSJvvf9R+5rzb5jF1Xx8E1X5mzx4pKjk1i6Ws77IbhDt3PfHKOMEJ1hBkkVrHsfwqP51M+M+AOYyLCyrvtOFf85MfrG3U7ifn78FPUyFMCe4sPQZBLF4hFIacqbZkfApIWjxdTpm/ap9ggUIwwLZqthQtmsSl8tNFqJvdslMRLhBBfys3L32XbUI0UWvyC2doeHwKLuEEnMV2Cmr8wJYltmujExnI5KbYbaKkQvyd4OEqp0XhHdX5roer4dpzudW/S21AgQ1GXsM1pcYGMCj1HzZjEAMdiLJXYbZQ9bosnVJ5E2I5YpGWPobxgw6xPiYNU0XbnCNGuPoO/cSFGlKgbukyqbrYVkF/ghg2+pEFcQYBfJVKSBhiyHoUobblEH0LaR5O3c0VgShevThuW9XWvW3fAF3UwujKi4PWKQUL4jDf/lUqvFYs
    REDIS_URL: AgAvlyOYTq3nFcmTQLs43kCypaIfrZCxYnsnmZgXbUBfDRrRIt1wkwQfeEzUAeYubB9eMZJMxfHmKi+wi/4NIAyaJjNKtUiw1k7Xc0o/Nvmq8iUaCuz3zVRI/F4txHZTrxjWPU/xE3dgpx3iaQZ9oHzM4CDhVhZb+MvuYzCS6/Q5ZzjVsPH8/K5J+fBjg+kcFVprexx+TP/eXYQn+dEi7mnjXrjHgELKXT5sj2aDN588vV2tfVk7yS6KnyHAEc1owDuCp6AedhNBnAS0hIXept/AvFBSNB40rCeheRXCKjPNGy87IAuFJwX5h49a29rWtbGfDajOtbBoJYkaAdiW4+tKdLD+2OgTJ/Hh+hf5Z8LlY073U8ccR2Cq9bNwPtUt5Y8wlbOJbGSfBs8gUSUrFYm0Ku0aHvZP7FiWH/v7Bz8phu9kPeXnA00zJ/XD+9D2gasNcQ535w5UK6oqZA+EIEt2Y2p7z7FPj3iRdhS14aUJGR97WNTiTHg9ouGYtwDl+I8KDFNYJWP7RAFybvpDhonSZZrHsZELGPCjfk1XbKSuOhLpjfn9eSgZicc0U2Fwr6uBPOdCHkz7AmHG4lYC6eWQhhIEWit/3cyueeFCcoKpvPKR9t794tzZ9QxHnzRSVX0L0JRD/iluObK9yu9PrSgrAd3ZpPP+/QxDat3AouUmEaVCRmZ+nL6VmV2Sl0eIBx81pRcUr1LBNjKMrvCW+FBsyBczslJr76FP31+ohLoUEpsIZATbtkYml8OwoGyY9jrHQdlQRk5+SR/8000SOL8=
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-secrets
        app.kubernetes.io/part-of: oms
        environment: production
      name: redis-secrets
      namespace: oms
    type: Opaque
