apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: oms
  labels:
    app: orders
    component: backend-service
    app.kubernetes.io/name: orders
    app.kubernetes.io/part-of: oms
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: grpc
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: metrics
  selector:
    app: orders
