apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: oms

resources:
- configmap.yaml
- secrets/
- gateway/
- orders/
- payments/
- stock/
- kitchen/
- customer-app/
- kitchen-display/
- ingress/
- monitoring/

commonLabels:
  app.kubernetes.io/part-of: oms
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  app.kubernetes.io/version: "1.0.0"
