apiVersion: v1
kind: Service
metadata:
  name: kitchen
  namespace: oms
  labels:
    app: kitchen
    component: consumer-service
    app.kubernetes.io/name: kitchen
    app.kubernetes.io/part-of: oms
spec:
  type: ClusterIP
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: kitchen
